### ISSUE TITLE
Can I have write access?

### ISSUE THREAD

**Issue by ScratchFakemon** [Scratch-Computing-Alliance/Scratch-Computing-Alliance.github.io#5]
For some reason, I don't have write access to this repo. It would be helpful, since I might need to update the website again.

**Comment by ScratchFakemon** [comment]
When I try to update something, I get this error: 
You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork ScratchFakemon/sca-website-update, so you can send a pull request.

**Comment by webbrowser11** [comment]
first of all, that is not an error. also, the reason you dont have write access is because the base permission is read. i have asked the owner to change it to write but he does not know how

**Comment by ScratchFakemon** [comment]
b r u h

**Comment by cWorksLLC** [comment]
done

**Comment by webbrowser11** [comment]
@cWorksLLC you cant give me edit access to?

**Comment by webbrowser11** [comment]
oh you did
